wandb_version: 1

save_path:
  desc: null
  value: /mnt/HDD/oci_models/aotgan
version:
  desc: null
  value: v1
cuda:
  desc: null
  value: '0'
num_workers:
  desc: null
  value: 4
wandb:
  desc: null
  value: 'yes '
pretrain:
  desc: null
  value: 'yes'
pretrained_model:
  desc: null
  value: premodel
error_signal:
  desc: null
  value: 'no'
ts_batch_size:
  desc: null
  value: 5
vs_batch_size:
  desc: null
  value: 2
learning_rate:
  desc: null
  value: 0.0001
epochs:
  desc: null
  value: 100
optimizer:
  desc: null
  value: Adam
scheduler:
  desc: null
  value: lambda
loss:
  desc: null
  value: ce
valid_epoch:
  desc: null
  value: 1
model:
  desc: null
  value: OCI-GAN
training_date:
  desc: null
  value: '240506'
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.4
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714968067.0
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      3:
      - 16
      - 17
      - 23
      4: 3.8.18
      5: 0.16.4
      6: 4.39.3
      8:
      - 5
      13: linux-x86_64
